### PR TITLE
Remove end-of-line from .editorconfig

### PR DESCRIPTION
**Pull request by rudyhuyn**
## Fixes #.
As mentioned here, https://github.com/Microsoft/calculator/issues/237#issuecomment-471230876, `crlf` is already automatically modified by `.gitattribute`, by removing this file we will:
- not change the behavior on Windows (git will replace CR and LF by CRLF)
- prevent issues on Mac/Linux.

There is no rational reasons to keep it, sometimes, less is more. (the only reason I think about is if a file is modified by 2 file editors on the same computer, but the odds are high that they already uses the same EOL).

### Description of the changes:
- remove the `end_of_line = crlf` from .editorconfig.

### CODE REVIEW

**Comment by HowardWolosky** [comment]
Thanks Rudy.

Looks like you're not up-to-date.  As opposed to this showing a diff of removing one line, you're making the same 2 file changes again (minus that one line).

Please get your fork up-to-date with master and then push an update to here.

**Comment by rudyhuyn** [comment]
Yes, my upstream was outdated. fixed

**Comment by rudyhuyn** [comment]
So now we have a diff ready if https://github.com/Microsoft/calculator/issues/237 is greenlighted by contributors!

**Comment by janisozaur** [comment]
Thanks

**Comment by rudyhuyn** [comment]
Thank you for your feedback!

**Pull request merged**
