### PR TITLE
Fixing incorrect Hungarian translation

### PR DESCRIPTION
**Pull request by Omcsesz**
## Fixes #.
There were two incorrect translations which I fixed.

### Description of the changes:
-
-
-

### How changes were validated:

-
-
-

### CODE REVIEW

**Comment by mcooley** [comment]
Unfortunately, we're not able to merge translation suggestions in this repo because of limitations in our tooling. I have filed an issue internally (44597944) to track this, and our localization team will review and apply these changes. Thank you for your contribution!

**Comment by Omcsesz** [comment]
@mcooley Can you please link the internal issue here?

**Comment by mcooley** [comment]
@Omcsesz the internal issue number is 44597944.

**Comment by Omcsesz** [comment]
> @Omcsesz the internal issue number is 44597944.

So you can not link internal issues, only their number, right?

**Comment by Omcsesz** [comment]
@mcooley It's OK

**Pull request closed without merging**
