### PR TITLE
Add headers missing for compilation with GCC

### PR DESCRIPTION
**Pull request by janisozaur**
Things that required such update included:
* `wstringstream`
* `setprecision`
* `SCODE_CODE`, `E_BOUNDS`
* Various SAL macros

### CODE REVIEW

**Comment by janisozaur** [comment]
This has been open for over two weeks now, can someone please review/merge?

**Comment by sanderl** [comment]
@janisozaur, sorry for the delay in getting your PRs reviewed. We will be getting to it very soon.

**Comment by tian-lt** [comment]
Thank you for proposing this PR, @janisozaur.
It's great to see CalcManager can get compiled by GCC.

The changes look good to me.
But what is the scenario that requests using GCC to build Calculator?
Or, people would just like to reuse CalcManager as it's written in standard C++ instead of C++/CX?

**Comment by janisozaur** [comment]
It's the latter. Locally i have test suite running and passing on Linux. In the past I contributed code to move mantissa from VLA to `std::vector`, but it wasn't merged due to unknown performance impact. In the long run I want to implement benchmarks that would fill this gap.

**Review by tian-lt — APPROVED** [review]

**Review by mcooley — APPROVED** [review]

**Pull request merged**
