### PR TITLE
Fix automatic scientific notation

### LINKED ISSUE #226: Automatic scientific notation can't be disabled
**Describe the bug**
In scientific mode scientific notation can be enabled by F-E button but can't be disabled if number have more than 2 zeros after decimal point. This automatic scientific notation is also enabled even on standard mode. Sometimes it's more useful and more readable if number stay in common decimal format instead of scientific notation. For example while calculating crypto currencies it is more useful to see 0.000005142857 where I can easily see 514 satoshi price than 5.142857e-6.

**Steps To Reproduce**
1. Switch to standard or scientific mode
2. Type 0.000036
3. Press divide symbol
4. Type 7
5. Press Enter
6. Pressing F-E is not changing output format

**Expected behavior**
- Stay in normal decimal format until I press F-E to switch to scientific notation
OR
- Show scientific notation but also enable F-E switch to indicate scientific notation mode with ability to disable F-E to show number in common decimal format
OR
- Add another switch to enable/disable automatic scientific notation if number conains more than defined number of zeros after decimal point
OR
- At disable automatic scientific notation in standard mode calculator at all and add another switch to enable/disable automatic scientific notation in scientific mode if numbers contains more than defined number of zeros after decimal point

**Device and Application Information (please complete the following information):**
 - OS Build: 10.0.17763.0
 - Architecture: X64
 - Application Version: 10.1812.10048.0

### PR DESCRIPTION
**Pull request by uhliksk**
## Fixes #226.
- Fix automatic scientific notation while F-E switch is disabled

### Description of the changes:
- Added Auto-E switch in scientific mode to force disable automatic scientific notation while F-E switch is disabled
- Added new hotkey "B" for Auto-E switch. Hotkey "B" was selected because is near existing "V" for F-E switch.

### How changes were validated:

- manual

### CODE REVIEW

**Comment by tdmllc1** [comment]
Liquid

**Comment by HowardWolosky** [comment]
Thanks for this contribution.

This PR includes a _behavior change_ to the app, and our team is standardizing on a flow where a _behavior change_ needs to have an associated Issue which will provide the opportunity for discussion and approval before we'll consider merging in the corresponding code change.

We are in the process of updating CONTRIBUTING.md and our PR templates to clarify this.  In the meantime, please open an Issue to track this so that we can start the discussion.  Our team members will be able to join in on the discussion on Monday.

**Comment by uhliksk** [comment]
I created issue #226 for this PR. Thank you.

**Comment by tdmllc1** [comment]
500000000000000 Liquid USD Withdraw Binance

**Comment by HowardWolosky** [comment]
Locking the PR so that conversation on the problem being addressed is discussed in the Issue, so that future PR discussion can be limited to the _implementation_ of the fix.

**Comment by HowardWolosky** [comment]
The associated issue has been approved by triage.  Unlocking this issue.  @uhliksk - can you update the conflicts in this PR, as well as update the implementation based on the discussion with @grochocki in the issue?

**Comment by uhliksk** [comment]
> The associated issue has been approved by triage.  Unlocking this issue.  @uhliksk - can you update the conflicts in this PR, as well as update the implementation based on the discussion with @grochocki in the issue?

Ok. I'll update the implementation later this week.

**Comment by danbelcher-MSFT** [comment]
Ping @uhliksk

**Comment by uhliksk** [comment]
> Ping @uhliksk

I'm preparing new PR as solution is much different now. I'll upload new code today (UTC).

**Comment by uhliksk** [comment]
Replaced by #446

**Comment by uhliksk** [comment]
> Ping @uhliksk

@danbelcher-MSFT Please check new solution.

**Pull request closed without merging**
