### PR TITLE
Update app version to 1908

### PR DESCRIPTION
**Pull request by sanderl**
Update the version of the app to 1908.

### CODE REVIEW

**Comment by Poopooracoocoo** [comment]
Is there an appx? ☺

**Comment by HowardWolosky** [comment]
> Is there an appx? ☺

There's an appxbundle available with every PR and every merge into master.  To find it, just click on the "Checks" tab of the PR and then click on "View more details on Azure Pipelines".  From there, click on the blue "Artifacts" button in the top-right and choose "appxbundle".

For this PR, here's the [direct link](https://dev.azure.com/ms/23383dcd-16bf-49fc-9556-1cb151958a4c/_apis/build/builds/34790/artifacts?artifactName=appxBundle&api-version=5.2-preview.5&%24format=zip).

**Comment by Poopooracoocoo** [comment]
Thank you so much Howard!

**Comment by ItzLevvie** [comment]
@Poopooracoocoo Instructions from https://github.com/microsoft/calculator/issues/543#issuecomment-505056530 should still work.

**Pull request merged**
