### PR TITLE
Introduce Finance Calculator

### LINKED ISSUE #806: Support basic interest rate calculations
I was really surprised that there is no support for basic financial formulas in standard Windows calculator. I tried to look for any relevant Github issues but couldn't find any.

**Proposal**
Create a basic "compound interest rate calculator" with or without payments.

**Goals**
In a basic case, allow the user to compute one of principal/interest rate/term/total given the other three values.

**Requested Assignment**
I would like to help implementing this feature.

If there is an interest in this, I can create a normal spec with wireframes.

### PR DESCRIPTION
**Pull request by Chips1234**
As of July 08th, 2020: The tips calculator is not done yet!! If anyone can help me with the BooltoVisibility converter, that would be great! (P.s. this is still a draft pr)

### Description of the changes:
-  A new calculation mode, "Financial"
-  Includes Compound Interest Calculator
-  A tip calculation mode (Not started as of 08th July)

### How changes were validated:

- Manual

Note: In code, Financial mode is always mentioned as "FinanceCalculator" for shortness and consistency.
Also, if you have an idea or can tell me how to use the BooleanToVisibility converter that would be nice. Thanks.

### CODE REVIEW

**Comment by Chips1234** [comment]
To change modes between tip calc and compound calc, there's a Combobox but it currently does not work as I can't figure out how to do grid visibility with BooleanToVisibility.

**Comment by Chips1234** [comment]
Also, what other kinds of financial calculation modes would you like to see? I guess if it has more then two modes, we can’t use a Boolean for the combo box.

**Comment by Chips1234** [comment]
Can someone take a look?

**Comment by mcooley** [comment]
Thanks for jumping into the code here--but I think there are many undecided details about how the feature should work which need to be resolved _before_ looking at the code. For example, I'm not sure that we should group both the compound interest and tips calculators under one "Finance" mode.

Let's follow this project's [new feature process](https://github.com/microsoft/calculator/blob/master/docs/NewFeatureProcess.md) and work on a spec document which describes how the feature will work. The spec document can be changed faster than the code can and it's easier to share more widely for feedback. Once that document looks good we can move into the "Implementation" phase and reopen this PR.

**Comment by Chips1234** [comment]
Spec pull made! Look at the [spec](https://github.com/microsoft/calculator-specs/pull/22) and go give some feedback!

**Comment by Chips1234** [comment]
Also, can anyone help me (see gif below, once one grid is loaded, another should collapse but that doesn't happen)?
Calculator Financial Mode Change

**Comment by joseartrivera** [comment]
> Also, can anyone help me (see gif below, once one grid is loaded, another should collapse but that doesn't happen)?
> Calculator Financial Mode Change

I think its a problem with this part of the code, you are setting the DataContext to be the GraphingCalcViewModel instead of your view model.

`
void MainPage::EnsureFinanceCalculator()
{
    if (!m_financeCalculator)
    {
        m_financeCalculator = ref new FinanceCalculator();
        m_financeCalculator->Name = L"FinanceCalculator";
        m_financeCalculator->DataContext = m_model->GraphingCalcViewModel;

        GraphingCalcHolder->Child = m_financeCalculator;
    }
}
`

**Comment by Chips1234** [comment]
Alright. Will look into it. Thanks

**Comment by Chips1234** [comment]
Hmm... Still happens...
Calculator Error 2

**Pull request closed without merging**
