### PR TITLE
Updating main minor version to 2312

### PR DESCRIPTION
**Pull request by volkcor**
## Fixes #.
N/A

### Description of the changes:
- updating Main minor version to 2312
-
-

### How changes were validated:

-
-
-

### CODE REVIEW

**Review by adrien-chaussabel — APPROVED** [review]

**Review by hanzhang54 — APPROVED** [review]

**Review by tian-lt — APPROVED** [review]

**Comment by tian-lt** [comment]
Looks like the pipeline has been somehow disabled.

**Pull request merged**
