### PR TITLE
Fix #563: Odd dependency cycle

### LINKED ISSUE #563: Odd dependency cycle in CalculatorEngine
There is an odd dependency in CalcEngine.

`CalculatorManager` inherits `ICalcDisplay` and implements a set of virtual calls it exposes, in particular `SetPrimaryDisplay`.
https://github.com/microsoft/calculator/blob/2517854836fee634a273adf3be72371cdb51ddaa/src/CalcManager/Header%20Files/ICalcDisplay.h#L13

When setting a mode in `CalculatorManager`, e.g. https://github.com/microsoft/calculator/blob/2517854836fee634a273adf3be72371cdb51ddaa/src/CalcManager/CalculatorManager.cpp#L208
`this` (here: an instance of `CalculatorManager`) gets passed as an argument to the newly created `CCalcEngine` as `ICalcDisplay` pointer and the engine is stored as `unique_ptr` member field of `CalculatorManager`.

In the destructor of `CalculatorManager`, a single function is called, `MemorizedNumberClearAll` which then invokes `ProcessCommand(IDC_MCLEAR)` on current engine, gets passed on to `CCalcEngine::ProcessCommandWorker`, to `DisplayNum`, to `CCalcEngine::SetPrimaryDisplay` and finally to `m_pCalcDisplay->SetPrimaryDisplay`, but here `m_pCalcDisplay` _was_ the instance of `CalculatorManager` that just got its destructor called.

https://github.com/microsoft/calculator/blob/2517854836fee634a273adf3be72371cdb51ddaa/src/CalcManager/CalculatorManager.cpp#L46
https://github.com/microsoft/calculator/blob/2517854836fee634a273adf3be72371cdb51ddaa/src/CalcManager/CalculatorManager.cpp#L475
https://github.com/microsoft/calculator/blob/2517854836fee634a273adf3be72371cdb51ddaa/src/CalcManager/CEngine/scicomm.cpp#L87
https://github.com/microsoft/calculator/blob/2517854836fee634a273adf3be72371cdb51ddaa/src/CalcManager/CEngine/scicomm.cpp#L133
https://github.com/microsoft/calculator/blob/2517854836fee634a273adf3be72371cdb51ddaa/src/CalcManager/CEngine/scidisp.cpp#L124
https://github.com/microsoft/calculator/blob/2517854836fee634a273adf3be72371cdb51ddaa/src/CalcManager/CEngine/scicomm.cpp#L837

It will likely differ by implementation on how exactly, but the [standard suggests](http://eel.is/c++draft/class.cdtor#4) that will invoke the pure virtual `ICalcDisplay::SetPrimaryDisplay`. In case of GCC I believe the vtable is already destroyed by the time you enter dtor's body.

My question is: why is it necessary to call `MemorizedNumberClearAll` in `CalculatorManager::~CalculatorManager()`? The calc manager and all its engines are going down anyway, maybe it's ok to just drop that and it should fix the described problem.

**Device and Application Information**
 - OS Build: 5.0.13.1
```
Get-AppxPackage : The term 'Get-AppxPackage' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:22
+ " - Architecture: $((Get-AppxPackage -Name Microsoft.WindowsCalculato ...
+                      ~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-AppxPackage:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
 ```
 - Architecture:
```
Get-AppxPackage : The term 'Get-AppxPackage' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:29
+ " - Application Version: $((Get-AppxPackage -Name Microsoft.WindowsCa ...
+                             ~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-AppxPackage:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```
 - Application Version: 
 - Region: pl-PL
```
Get-AppxPackage : The term 'Get-AppxPackage' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:41
+ " - Dev Version Installed: $($null -ne (Get-AppxPackage -Name Microso ...
+                                         ~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-AppxPackage:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```
 - Dev Version Installed:

### PR DESCRIPTION
**Pull request by janisozaur**
There was no discussion other than lone comment from friendly Microsoft Issue Bot and I'm curious to see what breaks, if anything.

Resolves #563

### CODE REVIEW

**Comment by janisozaur** [comment]
Yay, nothing broke in tests!

**Comment by janisozaur** [comment]
Ping. This has been up for almost two weeks without any comments. I'd like to see this merged (or rejected, given sufficient reason) before I work on https://github.com/microsoft/calculator/pull/544 again, to not let it bitrot again.

**Comment by HowardWolosky** [comment]
Sorry for the delay, @janisozaur -- I have this queued for review this week.

**Comment by HowardWolosky** [comment]
@janisozaur -- Your analysis seems spot on.  Thanks, and nicely done.  That being said, I want to bring in @joshkoon since he introduced that destructor during some refactoring back in Oct 2018, and there might be some context there that both of us are missing.

@joshkoon -- This was code you wrote ten months ago, so if you have nothing more to add here, I completely understand.  I just thought it might be useful to see if there was a specific scenario that you were trying to account for with calling `MemorizedNumberClearAll` on destruction (because if so, the fix is likely to clear things out a different way)...

**Comment by janisozaur** [comment]
@pi1024e fair point, addressed.

**Comment by janisozaur** [comment]
Ping.

**Comment by HowardWolosky** [comment]
I spoke with @joshkoon about this change in-person on Friday, and he believed that it was _probably_ a safe change to make, but thought that verifying behavior in multi-instance scenarios would be worthwhile before merging it in.  Since you're on Mac OS, I'll do some local verification today and provided that things look good, we'll merge this in tomorrow.

**Pull request merged**
