### PR TITLE
Refactored XAML x:Names

### LINKED ISSUE #62: Update Calc x:Name values to begin with uppercase
Any and all occurrences of x:Name should use Pascal-case. Right now, it is inconsistent between views. The reasoning is that x:Name converts the object to be accessible as a property of the current view and properties should be Pascal-cased. I think this issue is easily fixed with a regex + replace.

### PR DESCRIPTION
**Pull request by LanceMcCarthy**
### Description of the changes:
-Refactored all x:Names to use the generally accepted Pascal-Casing

### How changes were validated:
Unit Tests
Manual Tests

### CODE REVIEW

**Comment by LanceMcCarthy** [comment]
@HowardWolosky Here's the new PR, from branch specifically for the issue.

Once this is merged, I'll make sure my fork's master is up to date and will always make sure I don't commit to master by accident (note to self - don't do this stuff late at night).

**Comment by LanceMcCarthy** [comment]
@danbelcher-MSFT Thanks for the guidance to remove the commits. However, I couldn't rebase due to a conflict between pick and upfix commits.

I followed your guidance and did the rebase with the following git-todo setup:'

image

When continuing, it results in the following:

image


Should I mark them as resolved and force the merge? I'm horrible with git from the command line.

**Comment by danbelcher-MSFT** [comment]
When git attempts the rebase, it tells you there are merge conflicts.  Run `git status` and it will tell you which files have conflicts.
```cmd
> git status
interactive rebase in progress; onto af41a18
Last command done (1 command done):
   pick f6848a5 Completed View (Calculator.xaml)
Next command to do (1 remaining command):
   fixup 1b613ff Completed View (Calculator.xaml)
  (use "git rebase --edit-todo" to view and edit)
You are currently rebasing.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   src/Calculator/Controls/CalculationResult.cpp
        modified:   src/Calculator/Controls/OverflowTextBlock.cpp
        modified:   src/Calculator/Views/Calculator.xaml
        modified:   src/Calculator/Views/Calculator.xaml.cpp
        modified:   src/Calculator/Views/CalculatorProgrammerDisplayPanel.xaml
        modified:   src/Calculator/Views/CalculatorProgrammerDisplayPanel.xaml.cpp
        modified:   src/Calculator/Views/CalculatorProgrammerOperators.xaml
        modified:   src/Calculator/Views/CalculatorProgrammerOperators.xaml.cpp
        modified:   src/Calculator/Views/CalculatorProgrammerRadixOperators.xaml
        modified:   src/Calculator/Views/CalculatorProgrammerRadixOperators.xaml.cpp
        modified:   src/Calculator/Views/CalculatorScientificAngleButtons.xaml
        modified:   src/Calculator/Views/CalculatorScientificAngleButtons.xaml.cpp
        modified:   src/Calculator/Views/CalculatorScientificOperators.xaml
        modified:   src/Calculator/Views/CalculatorScientificOperators.xaml.cpp
        modified:   src/Calculator/Views/CalculatorStandardOperators.xaml
        modified:   src/Calculator/Views/HistoryList.xaml
        modified:   src/Calculator/Views/MainPage.xaml
        modified:   src/Calculator/Views/NumberPad.xaml
        modified:   src/Calculator/Views/NumberPad.xaml.cpp
        modified:   src/Calculator/Views/UnitConverter.xaml
        modified:   src/Calculator/Views/UnitConverter.xaml.cpp

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

        both modified:   src/Calculator/App.xaml
```
So I can see that `App.xaml` has a conflict.  Open the file and resolve the conflict, then save the file.  Then:
```cmd
> git add src/Calculator/App.xaml
> git rebase --continue
```
And you keep following this process until all conflicts are resolved and the rebase can be completed.  Then force push your branch as before.

**Comment by danbelcher-MSFT** [comment]
ping @LanceMcCarthy.  Are we taking this change still?

**Comment by LanceMcCarthy** [comment]
Ugh, notification got lost in the noise, sorry. Will attempt this tonight.

**Comment by LanceMcCarthy** [comment]
@danbelcher-MSFT Hopefully I got it this time. Was able to manually handle the conflicts, there was some new stuff in there that wasn't really a conflict, just on differnet lines or added properties.

**Pull request merged**
