### PR TITLE
New look of `Calculator` in Windows 11

### PR DESCRIPTION
**Pull request by Dark-CodeX**

### CODE REVIEW

**Review by tian-lt — APPROVED** [review]

**Comment by Dark-CodeX** [comment]
Thanks for the approval @tian-lt. I would like to know when my *PR* is going to be committed to the `main` branch?

**Comment by tian-lt** [comment]
Thank you for submitting this PR, @Dark-CodeX.
The changes look good to me.

Feel free to complete this PR yourself. (*Squash and merge*)
Then, the changes will go to the main branch immediately.

*I'd like to complete the PR on behalf of you if you need it :-)*

**Comment by Dark-CodeX** [comment]
Thanks @[https://github.com/tian-lt], I don't have the write access. So, if you can merge this PR to the `main` branch please do it.

**Comment by tian-lt** [comment]
Sure, no problem.
Going to complete this PR.

**Comment by KiwiChess** [comment]
Hi,
my decimal point on the calculator keyboard screen has changed to a comma, how can i change it back to a decimal (period)
thanks for yr help
cheers kevin borg

**Comment by Dark-CodeX** [comment]
@KiwiChess I think this is happening because of country you have selected in Time & language section in Windows Settings app. I have selected India, you might have selected US or any other European country which uses a comma instead of a decimal.

**Pull request merged**
