### PR TITLE
Removed entrance transition for about button in NavigationView

### LINKED ISSUE #285: Main menu has multiple open animations
**Describe the bug**

Immediately after opening the app, upon clicking the upper left menu button, the menu expands with an animation that visually appears to move diagonally from the lower left corner of the app. After closing the menu, subsequent clicks to open the menu use a different animation that visually appears to move horizontally from the left edge of the app.

While it's very subtle, having different animations is visually confusing to me, when there is not an apparent reason (i.e. starting from two different states). Perhaps there is a reason that I missed; however, if the reason is not obvious, maybe it is not a good reason.

**Steps To Reproduce**

1. Open the Calculator app
2. Click the hamburger menu at top left
3. Observe the animation of the menu opening
4. Click menu again to close
5. Click menu again to open
6. Observe the different animation

**Expected behavior**

Every time the menu is opened from the normal state, it performs the same animation.

**Device and Application Information (please complete the following information):**
 - OS Build: 10.0.17134.0
 - Architecture: X64
 - Application Version: 10.1812.10048.0

**Additional context**

None

### PR DESCRIPTION
**Pull request by MahdiGhiasi**
### Description of the changes:
- Remove EntranceThemeTransition (which is a default transition for NavigationViewList) for the NavigationViewList on PaneFooter of NavigationView.

### How changes were validated:

- Manual testing

### CODE REVIEW

**Comment by MahdiGhiasi** [comment]
I'm not sure what the build failed message (Pipeline configuration error) means. Is it a configuration error on the repository itself or it's related to my change?

**Comment by mcooley** [comment]
The build failure looks like an intermittient thing--unrelated to your change. We'll figure out what went wrong and get it re-run.

**Comment by mcooley** [comment]
Closing and reopening to work around the build issue.

**Pull request merged**
