### PR TITLE
Added Hotkey Documentation #1814

### PR DESCRIPTION
**Pull request by WaveX-j**
### Description of the changes:
- Users faced an issue when trying to find the hotkeys or shortcuts for the Calculator App. Calculator App is a powerful tool that can be utilized well using the list of hotkeys provided, which will result in the overall improvement of the user experience.
- For easier reference, I added these hotkeys to the README.md file.
-

### How changes were validated:

- The changes were documentation, so the only testing done was through creating an HTML file to ensure the formatting was correctly done.
-
-

### CODE REVIEW

**Comment by WaveX-j** [comment]
> 

@microsoft-github-policy-service agree [company="{default}"]

**Comment by WaveX-j** [comment]
@microsoft-github-policy-service agree

**Comment by WaveX-j** [comment]
>
@microsoft-github-policy-service agree

**Comment by mcooley** [comment]
Thanks, but I don't think we're going to accept this change. See discussion in #1814.

**Pull request closed without merging**
