### PR TITLE
Add KeyboardAccelerators for AlwaysOnTop

### LINKED ISSUE #732: Keyboard accelerator to switch to On-Top mode
**Problem Statement**
Switching to On Top mode from the keyboard requires pressing the tab key many times until it focuses on the On-Top button, this is not very accessibility friendly.

**Evidence or User Insights**
This should be addressed since its very important to be accessible to all users, no matter what input they are using.

**Proposal**
Adding a simple keyboard accelerator can help solve this issue. It is important to make sure this shortcut wont clash with anything else. To increase discoverability it would make sense to have a tool-tip with the shortcut when hovering over the control.

**Goals**
The user should be able to use a keyboard shortcut to switch in to On-Top mode as well as switching out back to the regular view:
* <kbd>Alt</kbd>+<kbd>Up</kbd> = Enter Always-on-Top Mode
* <kbd>Alt</kbd>+<kbd>Down</kbd> = Exit Always-on-Top Mode

If possible, I would like to implement this idea if my proposal is accepted.

### PR DESCRIPTION
**Pull request by yaichenbaum**
### Description of the changes:
Added a keyboard accelerator to switch in and out of On-Top mode.
  * <kbd>Alt</kbd>+<kbd>Up</kbd> = Enter Always-on-Top Mode
  * <kbd>Alt</kbd>+<kbd>Down</kbd> = Exit Always-on-Top Mode

### How changes were validated:
Manually.

### CODE REVIEW

**Comment by HowardWolosky** [comment]
Locking this PR for the moment, as it's addressing an unapproved feature request.

**Comment by grochocki** [comment]
Unlocking, since issue was approved.

**Comment by rudyhuyn** [comment]
Hi Yair, it's good to see you here!

I will review your PR once the [change](https://github.com/microsoft/calculator/issues/732#issuecomment-548174871) requested by @grochocki done

If you have any questions, you already know how to contact me :)

**Comment by yaichenbaum** [comment]
@rudyhuyn Great to see you here as well! Am I supposed to do the change? I am happy to do it, I am just not familiar with the process.

**Comment by HowardWolosky** [comment]
@yaichenbaum - Thanks so much for the suggestion and the fix!

In the future, my recommendation is that you work off of a _branch_ in your fork as opposed to master.  Using branches allows you to work on multiple changes at once.  I've seen a lot of accidents happen in people's forks when they work directly in master.  Food for thought for next time.

**Comment by yaichenbaum** [comment]
@HowardWolosky I realized that as soon as I made the PR but I had already done it. Thanks for the tip.
There was one issue with the PR that I did't look in to fixing since I am not so familiar with this repo yet. I already pointed it out to @rudyhuyn but I will repeat it here for everyone else's benefit. After using the keyboard shortcut to switch in and out of On Top it focuses on the area shown on this picture.
image

**Comment by grochocki** [comment]
> After using the keyboard shortcut to switch in and out of On Top it focuses on the area shown on this picture.

This is expected when navigation occurs via keyboard. You'll notice that if you click on the "keep on top" button with a pointer device, that box _still_ has focus, but you won't see that focus rectangle. Some more info on that behavior [here](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.focusstate).

**Comment by yaichenbaum** [comment]
This is not the behavior when using the tab key and pressing enter on the button.
image

**Comment by grochocki** [comment]
Hmm, I think that should have been addressed in #677. @rudyhuyn?

**Comment by yaichenbaum** [comment]
Oh, when I checked this behavior I tested in the prod version, that must be why I saw this. When testing in Dev I see its all good.

**Pull request merged**
