### PR TITLE
Fix #407: Removed AppBar, OperatorTextBox and OperandTextBox controls

### LINKED ISSUE #407: Code Cleaning: AppBar, OperatorTextBox and OperandTextBox, TitleBar never used
**Cleaning**
The 3 following controls in Calculator/Controls are never used in the application.
- AppBar: https://github.com/Microsoft/calculator/search?q=AppBar&unscoped_q=AppBar
- OperatorTextBox: https://github.com/Microsoft/calculator/search?q=OperatorTextBox
- OperandTextBox: https://github.com/Microsoft/calculator/search?q=OperandTextBox

TitleBar and TitleBarHelper are used in different parts of the application (Memory, HistoryList, ...), but it seems like these controls have no effects on the app (old code from Windows 8/Windows Phone 8.1?)

### PR DESCRIPTION
**Pull request by jatinkumarg**
Removed AppBar, OperatorTextBox and OperandTextBox controls

### CODE REVIEW

**Comment by jatinkumarg** [comment]
@danbelcher-MSFT My recent commit got ```TF400898: An Internal Error Occurred```. (https://dev.azure.com/ms/calculator/_build/results?buildId=10301&view=results)

Do you know if it's because of my code or azure server issue?

**Comment by danbelcher-MSFT** [comment]
I'm not sure.  You can go to the 'Checks' tab and re-run the check:
image

**Comment by jatinkumarg** [comment]
It doesn't give me an option to ```re-run```. If possible can you give me authority to re-run it or just re-run it on my behalf?

image

**Comment by danbelcher-MSFT** [comment]
I had already tried re-running for you but the build has been queued for 17 minutes now.  We think the PR hit a bug in Azure Pipelines.  We'll contact the team tomorrow to do more investigation.  Sorry about the trouble!

**Comment by mcooley** [comment]
Closing and reopening to hopefully get the pipeline out of a bad state...

**Comment by danbelcher-MSFT** [comment]
@jatinkumarg, looks like the build works now.  You have some build errors to fix and then we can get your change merged.

**Comment by jatinkumarg** [comment]
@danbelcher-MSFT Everything seems fine now. Let me know if there are any further changes required.

**Pull request merged**
