### PR TITLE
Fixed x:Name instances

### LINKED ISSUE #62: Update Calc x:Name values to begin with uppercase
Any and all occurrences of x:Name should use Pascal-case. Right now, it is inconsistent between views. The reasoning is that x:Name converts the object to be accessible as a property of the current view and properties should be Pascal-cased. I think this issue is easily fixed with a regex + replace.

### PR DESCRIPTION
**Pull request by LanceMcCarthy**
## Fixes #62

Fixed camel cased x:Name, x:Uid names that were using camel-case with Pascal-case.

This also repairs the associated resource files and automation properties.

### Description of the changes:
- Renamed camel-case x:Name with Pascal case names
- Renamed camel-case x:Uid names with Pascal-case names and updated the linked resx resources and AutomationName items.

### How changes were validated:
This task was requested internally, added by the issue bot and directly assigned to me.

### Unit Tests
Ran the existing Unit Tests, All Tests Pass

image

### CODE REVIEW

**Comment by jlaanstra** [comment]
This will have loc impact. I like the x:Name changes but maybe we should remove the x:Uid changes for now.

**Comment by LanceMcCarthy** [comment]
@jlaanstra Can you post that comment in #62, I agree with you, but these tasks were lumped together (and is actually causing me a testing nightmare due tot he sheep amount of resource files)

**Comment by jlaanstra** [comment]
Done.

**Comment by LanceMcCarthy** [comment]
Can someone give this a run in another environment to confirm it works? I'm not able to get past a Type exception after app launch and wanted to eliminate if it's my fork or not.

**Comment by danbelcher-MSFT** [comment]
> Can someone give this a run in another environment to confirm it works? I think playing with the x:Uids has broken something unexpected
> Exception thrown: read access violation.
> **__abi_winrt_cast_to**(...) returned nullptr.

Hey @LanceMcCarthy, there are two instances of `Expressionborder` in OverflowTextblock.cpp that should be `ExpressionBorder`.  My debugger count the exception directly on the line that used the incorrect name.  If your debugger did not, I would start by looking at your exception settings to see if you disabled handling exceptions of this type.

**Comment by LanceMcCarthy** [comment]
@danbelcher-MSFT Fixed. Passes all tests and personal runtime use.

- Note I couldn't merge upstream master due to conflicts, so I've left that up to you.

**Comment by danbelcher-MSFT** [comment]
@LanceMcCarthy, Johan pointed out in #62 that updating the .resw files will cause loc handoff which incurrs cost for our team.  We agreed we don't want to pay the cost, meaning we need to revert all changes to resw files.  I again apologize for wasting your time making those updates.  Do you still want to continue with this PR, or do you want to leave it for someone else.  The correct change we want is updates only to `x:Name` attributes.

**Comment by LanceMcCarthy** [comment]
@danbelcher-MSFT I've accepted responsibility for the Issue and will complete it :) I have a commit when the x:Name changes were completed, I can probably move HEAD back to that commit.

However, I think it's better if I just re-fork the repo, so that we won't have to deal with these conflicts.

**Comment by LanceMcCarthy** [comment]
Reverting the x:Uid commits, or moving the HEAD, was _really_ messy even with a squash. I just started over and will submit a new PR from the new fork. This way we'll have a very clean history and no conflicts,

**Comment by janisozaur** [comment]
There's no need to re-fork or close the PR at all, you could simply replace the branch that makes up this PR with your updated version. Closing a PR or re-forking is rather annoying when you already have some discussion in the PR. I'd urge you to re-open this instead and use it with your updated version.

**Comment by LanceMcCarthy** [comment]
@janisozaur agreed, however, there's no way for me to change the source branch of a PR (I also made a couple of other bone-headed moves because I thought this was going to be a quick commit).

**Comment by janisozaur** [comment]
You still ended up pushing the fixed code into a branch that you used for creating a PR. A possible scenario for fixing that would have been:
1. `git reset --hard origin/master` to roll back whatever changes you may have made
2. Fix the code locally
3. Commit to the branch you used initially
4. `git push -f <your_remote>`

Or if you didn't want to roll back the changes you had, then:
1. Fix all the code locally
2. `git add` whatever was needed
3. `git commit --amend` to fix the latest commit on the currently used branch _or_ `git commit`, followed by `git rebase -if origin/master` to fix multiple commits
4. `git push -f <your_remote>`

There's no need to change the source branch of a PR.

**Pull request closed without merging**
