### PR TITLE
Update localized strings 2021-08-20

### PR DESCRIPTION
**Pull request by hanzhang54**
### Description of the changes:
Update strings from our internal localization system.

### CODE REVIEW

**Review by guominrui — APPROVED** [review]
LGTM

**Comment by onein528** [comment]
is this committed message machine transration?

**Comment by hanzhang54** [comment]
> is this committed message machine translation?
> 
> In Japanese, it is inconsistent with the message resources of other apps.

Our localization system is managed by our internal team and usually we get the translation from the localization system directly. If there is anything improper, could you please tell us more in details so that we can file the issue to the localization team? Thanks.

**Comment by onein528** [comment]
Localization system.. looks good to me!

But, One bad thing is that translation is not unified with other apps.

For example, the word “Light” translate to “明るい” or “白” and so on.

**Comment by grochocki** [comment]
@onein528 We are unable to accept localization fixes in the project, but if you have feedback on specific translations, please open a new issue, and we can route it to the internal team to address.

**Pull request merged**
