### PR TITLE
Clang format ci with format

### PR DESCRIPTION
**Pull request by janisozaur**
This is a duplicate of #405, this time with sources formatted (with `clang-format`s default settings) to prove the Azure Pipelines check works.

### CODE REVIEW

**Comment by janisozaur** [comment]
I will use this PR for testing of #405 until it's finished and close it afterwards.

**Comment by rudyhuyn** [comment]
IMO, the sorting of #include headers should ignore `pch.h` and always keep it at the top.

**Comment by janisozaur** [comment]
@rudyhuyn this is a demo only, please discuss the style in either #202 or #236

**Comment by mcooley** [comment]
See https://github.com/microsoft/calculator/pull/405#issuecomment-585921707

**Pull request closed without merging**
