### PR TITLE
Remove unneeded closing check

### PR DESCRIPTION
**Pull request by AtariDreams**
Turns out the check has not been needed since 2016.

### CODE REVIEW

**Review by mcooley — CHANGES_REQUESTED** [review]
Thanks for submitting this. This check is no longer necessary because FlyoutBase.Closing is available on all versions of Windows that Calculator supports. Instead of this cleanup change, we should remove this check, and then register for the Closing events directly in the XAML instead of in code-behind.

(Microsoft internal: here's [when this check was added in 2016](https://microsoft.visualstudio.com/Apps/_git/calculator.app.archive2/commit/4b1545fea8d458ac81ddbfb447f7bec287557404))

**Comment by AtariDreams** [comment]
Fixed @mcooley

**Comment by mcooley** [comment]
@AtariDreams can we register for the events in XAML instead of in the .cs file? I think it would be better to register for the `Closing` events in the same place we register for the `Closed` events: [here](https://github.com/microsoft/calculator/blob/edf08514a6773443bc75b8c3add497e1ab454ebe/src/Calculator/Views/Calculator.xaml#L692) and [here](https://github.com/microsoft/calculator/blob/edf08514a6773443bc75b8c3add497e1ab454ebe/src/Calculator/Views/Calculator.xaml#L790).

**Comment by AtariDreams** [comment]
@mcooley Done!

**Review by mcooley — APPROVED** [review]
Thanks!

**Pull request merged**
