### PR TITLE
Add utf8 bom to one file, and update a localized string(zh-CN).

### PR DESCRIPTION
**Pull request by llihua**
1.Add utf8 bom to the "CopyPasteManager.cpp" file.
2.Amend chinese localized strings for the word "Volume".

### CODE REVIEW

**Comment by HowardWolosky** [comment]
Thanks for your contribution, @llihua!

Regarding the BOM, we've had [previous discussions on BOM](https://github.com/Microsoft/calculator/pull/225#issuecomment-471222773), and at this time, we're not going to pursue normalizing or fixing BOM issues.

As for the localization suggestion, while [we cannot directly merge in localization suggestions](https://raw.githubusercontent.com/Microsoft/calculator/master/.github/ISSUE_TEMPLATE/localization_suggestion.md), on Monday I will get a workitem tracking this suggestion in our localization system, and then I will close this issue.

Thanks again for the contribution!

**Comment by HowardWolosky** [comment]
Unfortunately, our Localizaton system is not yet able to directly accept localization changes directly through this repo.  I've worked with our Localization team to identify a temporary workaround to make sure that this contribution isn't lost.  I have filed an issue in our internal tracking system (`21295854`) which tracks your suggested change, and the Localization team will use that internal issue to review and apply your changes via their system.

Your participation is very much appreciated, and your work _will_ get applied.  Unfortunately, I cannot directly merge this change in at this time.

**Comment by llihua** [comment]
> Unfortunately, our Localizaton system is not yet able to directly accept localization changes directly through this repo. I've worked with our Localization team to identify a temporary workaround to make sure that this contribution isn't lost.
> ...
I'm really a newer to C++/CX and UWP, and trying some new programming things. Thank you for your spending time to response.

**Comment by mcooley** [comment]
#496 includes the suggested change for "体积". Thanks again!

**Pull request closed without merging**
