### PR TITLE
Added two missing spaces

### PR DESCRIPTION
**Pull request by mikeshatch**
## Fixes #.
Missing spaces

### Description of the changes:
- Added missing spaces that weren't visible due to manual line breaks.

### CODE REVIEW

**Comment by HowardWolosky** [comment]
Not seeing any problem with the file being rendered as-is.  There's also no consistency with why you chose _these_ two lines to add trailing spaces to, but not others.  If you can point to specific MarkDown documentation that indicates that split-line paragraphs should have trailing spaces on those split lines, then I will certainly reconsider, but I'm not aware of any [documentation](https://daringfireball.net/projects/markdown/syntax) that indicates that.

**Comment by mikeshatch** [comment]
Hi Howard. Interestingly, it's not showing the missing space now for the first suggested correction. However, the second one still shows. Did you try saving it as a pdf? If you save it as a pdf you should see there is no space between "the" and "Security". Unless it's just buggy on my end.

**Comment by HowardWolosky** [comment]
Saving it as a PDF from GitHub? Or another viewer?  For instance, MarkdownPad explicitly renders a space there.  On GitHub, I reviewed the rendered HTML, and there is no explicit space that it inserts, but it still renders fine.  And if this was indeed an issue, there are _other_ lines in the README (and the other MarkDown files in this repo) that would need this same fix.

Again, I'm not inherently against making this change, but it's not clear to me why this change is just fixing _these two specific instances_, and looking more broadly, if this is an issue with our documentation, or rather the MarkDown renderer that you're viewing the content in.

**Comment by mikeshatch** [comment]
Saving it as a pdf via Google Docs. I didn't actually check the _other_ README files. Just this one. It's good this happened sooner rather than later because I think I'll avoid GitHub contributions of this nature in the future. Thank you.

**Comment by HowardWolosky** [comment]
Thanks Mike.  As I've mentioned, we want these docs to be as accessible and correct as possible...I'm simply unable to reproduce the specific problem that you're having.  I'd encourage you to open up a bug if you can come up with some clear repro steps for the problem, as it would better help me to understand the scope and impact of the issue.

**Pull request closed without merging**
