### PR TITLE
Fix the result in wrong number base while leaving and switching back …

### PR DESCRIPTION
**Pull request by hanzhang54**
…to Programmer

Issue: When switching from programmer to graphing/date/converters and switching back, 
1) the hex buttons are disabled even HEX in selection;
2) the number base selection is the same as when leaving but the result value is always in DEC;
3) the memory values are always displayed in DEC even the number base is not DEC when leaving programmer.

### Description of the changes:
Rename ResetDisplay() to ResetRadixAndUpdateMemory(). Reset radix to DEC for standard and scientific modes, and only update memory for programmer mode.

### How changes were validated:

Passed the unit tests and manually tested.

### CODE REVIEW

**Review by guominrui — DISMISSED** [review]
This fix looks good to me. But I suggest updating the ResetDisplay method name to be more specific, per the implementation of this method, it just resets radix related states.

**Review by guominrui — DISMISSED** [review]

**Review by tian-lt — APPROVED** [review]
Though I suppose there might be some different logics that don't re-initialize programmer mode, which caused this bug, it looks good to me to have such minimum changes to fix this issue. But if there's any chance, it would be great if we can spend some efforts to take a closer look to below cases that reset programmer mode differently(comparing with switching from standard mode to programmer mode)
 - From graphing mode to programmer mode.
 - From Date Calculation mode to programmer mode.

**Comment by hanzhang54** [comment]
> Though I suppose there might be some different logics that don't re-initialize programmer mode, which caused this bug, it looks good to me to have such minimum changes to fix this issue. But if there's any chance, it would be great if we can spend some efforts to take a closer look to below cases that reset programmer mode differently(comparing with switching from standard mode to programmer mode)
> 
> * From graphing mode to programmer mode.
> * From Date Calculation mode to programmer mode.



> Though I suppose there might be some different logics that don't re-initialize programmer mode, which caused this bug, it looks good to me to have such minimum changes to fix this issue. But if there's any chance, it would be great if we can spend some efforts to take a closer look to below cases that reset programmer mode differently(comparing with switching from standard mode to programmer mode)
> 
> * From graphing mode to programmer mode.
> * From Date Calculation mode to programmer mode.

The standard, scientific and programmer share the same view mode. There is one issue https://github.com/microsoft/calculator/issues/114 which describes the cleared input when switching among those three modes. So when switching from standard to programmer as you said, the result will get cleared. 

However, this is not the same issue addressed here. The problem here is when switching from graphing/date/converters to programmer, the result is retained but is not in the same number base as the selected number base if the selected number base is not DEC when leaving programmer.

The reason we do ResetDisplay() to standard and scientific is that standard and scientific modes only support DEC number base. In ResetDisplay(), it will disable the HEX buttons, set current radix type to DEC number base, set radix to DEC number base for CalculatorManager, and update numbers in memory to current radix. These operations are not needed when switching to programmer mode. So it would be a better way to correct the logic here by removing it.

**Comment by hanzhang54** [comment]
The memory is shared among standard, scientific, and programmer modes. The memory in programmer should not support the decimal number with point while the memory in standard and scientific modes should.

Removing the ResetDisplay() when switching to programmer would cause another issue. In this case, the decimal number with point saved in standard/scientific mode will keep the point in programmer. To avoid this, rename ResetDisplay() to ResetRadixAndUpdateMemory(), discard the radix resetting but keep the memory updating part in programmer mode.

**Review by guominrui — APPROVED** [review]
LGTM

**Pull request merged**
