### PR TITLE
Feat/programmer signedness

### LINKED ISSUE #66: Programmer mode on Calculator supports unsigned values
**Problem Statement**
Programmers need to work with both signed and unsigned values. Calculator is currently optimized for signed values only.

**Evidence or User Insights**
For example, while calculator will works on INT64 numbers, if I try to paste in a UINT64 value, e.g. 18403114778001080163, it shows as invalid input. Also, currently, the Bit Flip pane only supports signed numbers (the most significant bit is the Sign bit). Unsigned number support is a gap in our programmer mode.

For example, "256" does not fit into a single byte (requires a word):
image

**Proposal**
Add support for unsigned values in programmer mode.

**Goals**
* Support both signed and unsigned values in programmer mode.
* Support the option to switch between working with signed and unsigned values.
* All applicable operations should adapt to signed/unsigned status.
* Ensure that terminology is consistent with standards when referring to types like QWORD, DQORD, WORD, and BYTE (these terms generally refer to the unsigned versions).

**Non-Goals**
* None

**Low-Fidelity Concept**
image

**Requested Assignment**
I'm just suggesting this idea.  I don't want to implement it.

### PR DESCRIPTION
**Pull request by timlassiter11**
### Description of the changes:
- Added signedness toggle to UI
- Updated max values in CalcEngine when in unsigned mode
- Updated max values in CopyPasteManager when in unsigned mode
- Disabled ability to paste negative numbers when in unsigned mode
- Disabled negate button when in unsigned mode

### How changes were validated:
- Manually tested
- Entered values outside of signed int range while in signed and unsigned modes for all bit lengths
- Pasted values outside of signed int range while in signed and unsigned modes for all bit lengths
- Pasted negative numbers while in signed and unsigned modes

Attempted to run automated testing to ensure no functionality was broken but it appears some element IDs have changed and the tests do not work at the moment.

### CODE REVIEW

**Comment by rudyhuyn** [comment]
Thank you very much for this PR, as a developer myself, I would love the calculator to have this feature. 

Having said that, the UI/UX for this feature hasn't been specified yet (see https://github.com/microsoft/calculator-specs/):

Should we use a checkbox? Should we modify the Byte/Word/DWord button to display a flyout menu including an option unsigned/signed)? What should be the behavior of Calculator when users switch from one mode to another (should we recalculate the Dec/Hex/Oct values when the Bin value is the one selected? What should we do when Dec, Hex or Oct is selected?) or what should we do and display if the user types "10 - 99" when in unsigned mode?

To save time and not wait to review your PR , I would suggest to work in 3 steps.

**Step 1: Modify CalcEngine to support signed numbers**
I'm going to do a code review of the CalcEngine part this weekend, but we won't be able to modify the UI before the specifications are written. Once reviewed and approved, we will merge your PR to master.

**Step 2: Specifications written and approved by the community and Microsoft

**Step 3: Modify CalcViewModel and Calculator to let users access to this new feature

Let me know what you think!

Rudy

**Comment by timlassiter11** [comment]
@rudyhuyn - I hadn't thought about all of the potential UI/UX implementations. I developed this for my own use and just did what made sense to me. Once I had it working I figured I'd share it. What you suggested sounds great to me. I'd love to see this feature get implemented in the official build and I'd be happy to help however I can. Just let me know!

Tim

**Comment by rudyhuyn** [comment]
Specs for this features are still missing. Feel free to suggest your ideas and/or specs following [these instructions](https://github.com/microsoft/calculator/issues/66#issuecomment-526409602).

Thanks again @timlassiter11, we will reopen this PR once the specs for this feature done.

**Comment by 89z** [comment]
https://github.com/microsoft/calculator/issues/1418
https://github.com/microsoft/calculator/issues/66

https://github.com/microsoft/calculator/pull/974

**Pull request closed without merging**
