### PR TITLE
Improved performance on TraceLogger.cpp

### PR DESCRIPTION
**Pull request by Terottaja**
no need to thank me microsoft, hire me now

### Description of the changes:
- improved performance by undefining SEND_TELEMETRY
-
-

### How changes were validated:

- Tested the application and no apparent bugs were present
-
-

### CODE REVIEW

**Comment by KamranMackey** [comment]
Bad bait.

**Comment by xyzzer** [comment]
What's the measured performance impact and improvement after the change?

**Comment by azz0r** [comment]
Be nice to know why this was closed 👍

**Comment by HowardWolosky** [comment]
Microsoft's [privacy statement](http://go.microsoft.com/fwlink/?LinkId=521839) covers how data collection works.

**Comment by mike-bailey** [comment]
Perhaps more constructively - why does a calculator need to collect usage data? Is the idea if less people use multiplication it’ll somehow change the course forward for a calculator?

**Comment by HowardWolosky** [comment]
You are welcome to review the set of data that we collect and extrapolate how it might influence product decisions.  It is all defined as part of the file that was in this PR.

An example of something that is tracked: how long it takes for the app to launch.  Statistical analysis of that data enables us to determine how to improve the product, especially if we are able to associate a change in launch time to a specific changelist.

**Comment by rudyhuyn** [comment]
One of the positive aspects of an open-source project is that you can fork it, remove the parts you don't like, build and use your own version! Feel free to do it!

**Comment by mike-bailey** [comment]
Well, yes, I believe that's what this fork was 😄 (not saying it should be accepted, just that it's been done)

**Comment by luciusmagn** [comment]
The real question is why tf would a calculator collect data :^)

**Pull request closed without merging**
